### ISSUE TITLE
root文件夹下的目录打开错误

### ISSUE THREAD

**Issue by asd519627326** [trueai-org/mdrive#1]
docker安装，linux中展开root文件夹，显示子文件夹时出错
![Uploading capture_20240111193513166.jpg…]()

**Comment by trueai-org** [comment]
感谢您的反馈。

1、确保没有使用只读模式，只读模式无法加载，不要配置：-e READ_ONLY=true，如果映射了 appsettings.json，请检查 appsettings.json 中的配置 ReadOnly: null
docker run --name mdrive -d --restart=always \
 -v /home/mdrive/appsettings.json:/app/appsettings.json \
 -p 8080:8080 trueaiorg/m-drive-sync-client

2、如果仍然不可以，可以重新拉取最新版 docker
docker pull trueaiorg/m-drive-sync-client

3、体验地址，目前测试最新版是没有问题的。
http://43.129.20.214:18080/

![image](https://github.com/trueai-org/MDriveSync/assets/37255565/c1116067-38f3-4500-bd20-50155edac6f4)

**Comment by trueai-org** [comment]
v1.4.0 已修复
