### ISSUE TITLE
请问有计划支持2GB以上文件大小的同步嘛？

### ISSUE THREAD

**Issue by xray447** [trueai-org/mdrive#10]
我在尝试同步一个7GB大小的文件的时候出现了
System.IO.IOException: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.

看起来是ReadAllBytesAsync不支持2GB以上的文件
请问有计划支持2GB以上文件大小的同步嘛？

**Comment by xray447** [comment]
看见路线图了，请问这个issue我是留在这里以获得持续更新还是直接关掉？

**Comment by trueai-org** [comment]
感谢您的建议，这个问题暂时不用关掉，修复后可以再验证下。

**Comment by trueai-org** [comment]
v2.0.0 已修复，感谢！！
