### ISSUE TITLE
程序意外中断闪退

### ISSUE THREAD

**Issue by InnerBarriers** [trueai-org/mdrive#11]
在备份大文件夹（包含上万个文件）的过程中，程序中途MDriveSync.Client.API.exe闪退。

以下几个阶段均发生过闪退情况：
1. 文件读取、准备过程
2. 文件上传过程

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/376b0a5e-e3c4-439b-94d1-36c56f357aec)
![image](https://github.com/trueai-org/mdrive/assets/37255565/8be4a08d-8d49-4ed0-8431-664991b5d3ed)

感谢您的反馈，如图所示，经测试目前并未发现异常。
是否能提供 logs 目录下的日志或程序错误日志。
