### ISSUE TITLE
Windows版本是否支持加密上传

### ISSUE THREAD

**Issue by mechenik** [trueai-org/mdrive#16]
在配置界面没有加密相关得配置信息

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/022d2b30-4c4c-43f8-b047-5bc81a3e34ab)

v1.6.0 才支持，近期即将发布。

**Comment by trueai-org** [comment]
v2.0.0 已提供支持，非常感谢。
