### ISSUE TITLE
新特性 | 希望支持像OneDrive一样同步本地文件夹

### ISSUE THREAD

**Issue by srsng** [trueai-org/mdrive#17]
OneDrive同步的策略主要特点在于，备份文件夹中的文件（文件夹）被修改才会被重新上传，比较灵活。
对于mdrive现有的策略，**似乎**是完全重新扫描文件夹并读取云端文件数据并比对，具体使用上这样也比较笨重，备份很慢。

everything可以获取本地最新被修改文件的相关数据（视图>排序>修改时间)，或许有其他可以获得这些信息的系统api。

希望mdrive未来能够支持类似OneDrive的同步策略：先把备份文件夹中所有文件上传（初始备份），然后持续监控相关路径的修改情况，并对被修改的文件即时（或一定延时）后云同步。

**Comment by trueai-org** [comment]
![image](https://github.com/trueai-org/mdrive/assets/37255565/9ed045c2-7c8c-41a2-8ed7-34c4376ced50)

感谢您的建议，目前是有文件监听功能的，但是考虑到文件监听需要持续保持软件运行，如果遇到服务器异常、高频文件等极端情况，可能导致监听触发事件过于频繁。
因此目前还在优化此相关功能，考虑到 **完全重新扫描文件夹** 目前性能上足够，而且很快（1~分钟级别）。
通过底层控制获取文件有更快的方式，例如针对 NTFS 系统的 **FFS**。
考虑到设计的复杂性，会在之后继续优化。

**Comment by srsng** [comment]
好，就作业工作状况提示来看卡顿主要在“获取云盘文件”，期待后续优化.
