### ISSUE TITLE
Docker部署怎么数据持久化

### ISSUE THREAD

**Issue by 616734202** [trueai-org/mdrive#2]
在docker中部署后，删除容器再创建容器，之前设置的存储和作业就消失了。
`sudo docker run --name mdrive -d --restart=always \
 -v /MDriveSync/appsettings.json:/app/appsettings.json:rw \
 -v /MDriveSync/appsettings.Client.json:/app/appsettings.Client.json:rw \
 -v /MDriveSync/logs:/app/logs \
 -v /data:/data:ro \
 -e BASIC_AUTH_USER=admin -e BASIC_AUTH_PASSWORD=123456 \
 -p 8080:8080 trueaiorg/m-drive-sync-client`

另外appsettings.json没有找到示例
appsettings.Client.json感觉没什么用

**Comment by trueai-org** [comment]
感谢，已收到您的问题。
1、这是 `appsettings.json` 的示例，这里主要配置默认授权、日志等，如果使用 docker，可以不用配置。

```
{
  "ReadOnly": null,
  "BasicAuth": {
    "User": "",
    "Password": ""
  },
  "Client": {
    "AliyunDrives": [
    ]
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Default": "Warning",
        "System": "Warning",
        "Microsoft": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "File",
        "Args": {
          "path": "logs/log.txt",
          "rollingInterval": "Day",
          "fileSizeLimitBytes": null,
          "rollOnFileSizeLimit": false,
          "retainedFileCountLimit": 31
        }
      }
      //{
      //  "Name": "Console"
      //}
    ]
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "urls": "http://*:8080"
}

```
2、`appsettings.Client.json` 是用于首次初始化的默认启动配置（可能存在 bug），现在系统更新了，默认使用数据库存储了，数据库默认存在当前目录的 `db` 目录下，因此，如果需要持久化，建议启动实例如下：


```
docker run --name mdrive -d --restart=always \
 -v /home/mdrive/db:/app/db:rw \
 -e BASIC_AUTH_USER=admin -e BASIC_AUTH_PASSWORD=123456 \
 -e READ_ONLY=true \
 -p 18080:8080 trueaiorg/m-drive-sync-client
```

**Comment by trueai-org** [comment]
确保映射的目录有写入权限，db 示例：
![image](https://github.com/trueai-org/MDriveSync/assets/37255565/9c05ad06-02ba-468b-b843-f0d7a73bef9d)

**Comment by 616734202** [comment]
非常感谢，已完美解决我的问题，这是非常好用的一款工具，我会推文推广一下。

**Comment by trueai-org** [comment]
谢谢支持，当前工具还在不断的完善中，接下来会完善相关文档和新功能的支持。
