### ISSUE TITLE
WEB界面中translateelement.css不能加载的问题

### ISSUE THREAD

**Issue by 616734202** [trueai-org/mdrive#3]
系统：ubuntu
使用docker部署，打开web界面后，网页标签很长一段时间在转圈，F12调试后发现有个css加载超时：
`<link type="text/css" rel="stylesheet" charset="UTF-8" href="https://translate.googleapis.com/translate_static/css/translateelement.css">`
挂梯子后访问404
![image](https://github.com/trueai-org/MDriveSync/assets/7934613/bd389c12-2f36-4e5f-bca4-005acc5d1c92)

**Comment by 616734202** [comment]
<link type="text/css" rel="stylesheet" charset="UTF-8" href="https://translate.googleapis.com/translate_static/css/translateelement.css">

**Comment by 616734202** [comment]
https://translate.googleapis.com/translate_static/css/translateelement.css

**Comment by 616734202** [comment]
另外，我创建了2个事务（A和B），设置的目标目录（云盘存储路径）都为backup（设置相同），在处理其中1个事务时，另一个事务同步的文件会被清理掉？

**Comment by trueai-org** [comment]
1、是不是端口映射错了，web ui 不会加载个 css 的
2、使用镜像的方式，目前确实会存在这个 bug，后期会准备添加检查，防止不同的作业，选择同一个备份目录。
镜像同步，是以本地为主，因此发现远端与本地不一致，会删除远端数据。
![image](https://github.com/trueai-org/MDriveSync/assets/37255565/b591bf04-18cf-4559-919d-a6d44c645f11)

**Comment by 616734202** [comment]
1、应该是我浏览器的问题，换了一个浏览器后没有加载。
