### ISSUE TITLE
删除作业逻辑问题

### ISSUE THREAD

**Issue by 616734202** [trueai-org/mdrive#4]
您好，docker部署创建作业后，不能操作删除，显示操作成功，但是作业还在，会变成禁用状态。
重启容器后，才可以进行作业的删除。

**Comment by 616734202** [comment]
其他业务也会都不能删除

**Comment by 616734202** [comment]
重启容器后，重启前的作业可以删除，重启后新建的不能删，需要再重启才可以。

**Comment by trueai-org** [comment]
感谢，经过测试确认存在这个 BUG，目前已修复，将会在下个版本验证。

**Comment by 616734202** [comment]
好的

**Comment by trueai-org** [comment]
v1.4.0 已修复
